<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            'Addalaichenai',
            'Adhikarigama',
            'Agalawatte',
            'Ahangama',
            'Akkaraipattu',
            'Akiriyankumbura',
            'Alimankada (Elephant Pass)',
            'Aluthgama',
            'Ambalantota',
            'Ambepussa',
            'Ampara',
            'Ampara Junction',
            'Amunekandura',
            'Andaulpatha',
            'Anuradhapura',
            'Arankale / Aranthalawa',
            'Arasadi',
            'Arasadi Junction',
            'Arayampathy',
            'Athiliwewa',
            'Avissawella',

            'Bakinigahawela',
            'Balangoda',
            'Bambaginna',
            'Bambalapitiya',
            'Batticaloa',
            'Beragala',
            'Bibile',
            'Buduruwagala Junction',
            'Buttala',

            'Chagakachcheri (Chavakachcheri)',
            'Chedpalayam',
            'Chenkalady',
            'China Bay',
            'Colombo',

            'Dambana',
            'Dambulla',
            'Dehiwala',
            'Devinuwara',
            'Digana',
            'Dikwella',
            'Dombagahawela',

            'Eheliyagoda',
            'Emporium',
            'Eravur',

            'Galabedda',
            'Galkulama',
            'Galle',
            'Galewela',
            'Gandara',
            'Ganewalpola',
            'Godakawela',
            'Gonagolla',

            'Habaraduwa',
            'Habarana',
            'Haldummulla',
            'Hambantota',
            'Handapanagala Junction',
            'Hanwella',
            'Haragama',
            'Harasgala',
            'Hasalaka',
            'Hulannuge',
            'Hulandawa',
            'Hungama',
            'Hunnasgiriya',

            'Ibbagamuwa',
            'Iranamadu',

            'Jaffna',

            'Kadawatha',
            'Kadugannawa',
            'Kaduruwela',
            'Kaduwela',
            'Kahaella Bridge',
            'Kahawatta',
            'Kala Oya',
            'Kalawana',
            'Kalawanchikudy',
            'Kallady',
            'Kallaru',
            'Kalmunai',
            'Kalkudah',
            'Kaluthavalai',
            'Kaluwanchikudy',
            'Kamburugamuwa',
            'Kandy',
            'Karadiyanaru',
            'Karadugala',
            'Karaitivu',
            'Karuwalagaswewa',
            'Kathiraveli',
            'Kattankudy',
            'Katugoda',
            'Keerthibandarapura',
            'Kegalle',
            'Kelaniya',
            'Kilinochchi',
            'Kilivetti',
            'Kinniya',
            'Kiran',
            'Kirankulam',
            'Kithulkote',
            'Koddai Kallaar',
            'Koddammunai',
            'Kodikamam',
            'Koggala',
            'Kokavil',
            'Kolonwinna Junction',
            'Komari',
            'Kommathurai',
            'Kosgama',
            'Koslanda',
            'Kottukulam Junction',
            'Kotiyagoda',
            'Kuda Oya',
            'Kulawankeni Junction',
            'Kumbalgama',
            'Kumbukgana',
            'Kumbukkana',
            'Kurukkalmadama',
            'Kurunegala',
            'Kuruwita',

            'Lahugala',
            'Lunugamvehera',

            'Madampe',
            'Madugama (Matugama)',
            'Madugasmulla',
            'Mahaiyawa / Medagama',
            'Mahakalugolla',
            'MahaOya',
            'Mahawela',
            'Mahiyanganaya',
            'Manampitiya',
            'Mankulam',
            'Mannar',
            'Maradana',
            'Maradankadawala',
            'Marakolliya',
            'Maruthamunai',
            'Matale',
            'Matara',
            'Mawanella',
            'Medamahanuwara',
            'Medawachchiya',
            'Meegaswatta',
            'Meeravodai',
            'Melsiripura',
            'Mihintale',
            'Minneriya',
            'Mirissa',
            'Mirusuvil',
            'Monaragala',
            'Mullegama',
            'Murakkoddanchenai',
            'Mutur',

            'Nakkala',
            'Nakulugamuwa',
            'Namaloya Junction',
            'Naula',
            'Navalady',
            'Netolpitiya',
            'Nintavur',
            'Nittambuwa',
            'Nivitigala',
            'Nochchiyagama',
            'Nonagama',
            'Nonagama Junction',
            'Nupe Junction',

            'Obegoda',
            'Oddamavadi',
            'Oluvil',
            'Omanthai',
            'Onthachimadam',
            'Orugodawatta',

            'Padiyatalawa',
            'Pahariya',
            'Palai',
            'Palamunai',
            'Palavi',
            'Pallebedda',
            'Pallemalala',
            'Pannegamuwa',
            'Paranthan',
            'Pasikuda',
            'Pasyala',
            'Paturaliya',
            'Pelmadulla',
            'Pelwatta',
            'Pelwatte',
            'Peradeniya',
            'Periya Kallaar',
            'Pilimatalawa',
            'Pillaiyaradi',
            'Polgahawela',
            'Polonnaruwa',
            'Poppitiya',
            'Pottuvil',
            'Puliyankulam',
            'Pullumalai',
            'Punani',
            'Puttalam',

            'Rajagalatenna',
            'Rambewa',
            'Randenigala',
            'Ranna',
            'Rathmalyaya',
            'Ratnapura',
            'Ridetenna',

            'Sainthamaruthu',
            'Saliyawewa',
            'Sammanthurai',
            'Sangamankanda',
            'Santhiveli',
            'Sathurukondan',
            'Serankada',
            'Serunuwara',
            'Sirigala',
            'Siyambalanduwa',

            'Talpe',
            'Tangalle',
            'Tannammunai',
            'Teldeniya',
            'Telulla',
            'Thalankudah',
            'Thalaramba',
            'Thambiluvil',
            'Thampadayi',
            'Thanamalwila',
            'Thavapuram',
            'Thennekumbura',
            'Thettativu',
            'Thillayadi',
            'Thirappane',
            'Thirikkonamadu',
            'Thirukkovil',
            'Trincomalee',

            'Udawalawe',
            'Udamalala',
            'Ududumbara',
            'Uhana',
            'Unawatuna',

            'Vakarai',
            'Valaichchenai',
            'Valaichchenai Junction',
            'Valgama',
            'Vavuniya',
            'Veherayaya',
            'Veliyaya',
            'Verugal',
            'Vinayagapuram',

            'Weerawila',
            'Weligama',
            'Weligatta',
            'Welikanda',
            'Welipenna',
            'Wellampitiya',
            'Wellawatte',
            'Wellawaya',
            'Wirawila',

            'Yakkala',
        ];

        foreach ($locations as $name) {
            Location::updateOrCreate(
                [
                    'name' => trim($name),
                ],
                [
                    'district' => '',
                    'province' => '',
                    'latitude' => 0,
                    'longitude' => 0,
                    'is_active' => true,
                ],
            );
        }
    }
}