<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
Schema::create('bookings',function(Blueprint $t){$t->id();$t->foreignId('trip_id')->constrained()->cascadeOnDelete();$t->foreignId('passenger_user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('booking_reference')->unique();$t->json('seat_numbers');$t->unsignedTinyInteger('passenger_count');$t->decimal('subtotal',10,2);$t->decimal('discount',10,2)->default(0);$t->decimal('total',10,2);$t->enum('payment_status',['pending','paid','failed','refunded'])->default('pending');$t->enum('status',['confirmed','cancelled','completed','no_show'])->default('confirmed');$t->timestamps();});
Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('booking_id')->constrained()->cascadeOnDelete();$t->string('transaction_id')->unique();$t->decimal('amount',10,2);$t->enum('method',['card','mobile','bank','cash']);$t->enum('status',['pending','success','failed','refunded'])->default('pending');$t->timestamp('paid_at')->nullable();$t->string('gateway_reference')->nullable();$t->timestamps();});
Schema::create('notifications',function(Blueprint $t){$t->id();$t->foreignId('operator_id')->nullable()->constrained()->nullOnDelete();$t->enum('target_type',['all','operators','passengers','operator'])->default('all');$t->string('title');$t->text('message');$t->timestamp('sent_at')->nullable();$t->timestamps();});
Schema::create('live_locations',function(Blueprint $t){$t->id();$t->foreignId('trip_id')->constrained()->cascadeOnDelete();$t->decimal('latitude',10,7);$t->decimal('longitude',10,7);$t->decimal('speed_kmh',6,2)->nullable();$t->timestamp('recorded_at');$t->index(['trip_id','recorded_at']);});
Schema::create('emergency_alerts',function(Blueprint $t){$t->id();$t->foreignId('operator_id')->constrained()->cascadeOnDelete();$t->foreignId('trip_id')->constrained()->cascadeOnDelete();$t->foreignId('staff_id')->nullable()->constrained('staff')->nullOnDelete();$t->text('message')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->enum('status',['open','resolved'])->default('open');$t->timestamp('resolved_at')->nullable();$t->timestamps();});
Schema::create('system_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('module');$t->text('description')->nullable();$t->string('ip_address',45)->nullable();$t->timestamp('created_at')->useCurrent();});
} public function down():void{foreach(['system_logs','emergency_alerts','live_locations','notifications','payments','bookings'] as $x)Schema::dropIfExists($x);} };