<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
Schema::create('operators',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('company_name');$t->string('owner_name');$t->string('phone');$t->string('email');$t->string('address')->nullable();$t->string('permit_or_registration_no')->nullable();$t->enum('status',['pending','active','inactive'])->default('pending');$t->boolean('is_published')->default(false);$t->timestamps();});
Schema::create('buses',function(Blueprint $t){$t->id();$t->foreignId('operator_id')->constrained()->cascadeOnDelete();$t->string('bus_number')->unique();$t->string('bus_name')->nullable();$t->string('route_permit_number');$t->unsignedSmallInteger('seat_count');$t->enum('bus_type',['Normal','Semi-Luxury','A/C']);$t->text('facilities')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('seats',function(Blueprint $t){$t->id();$t->foreignId('bus_id')->constrained()->cascadeOnDelete();$t->string('seat_number');$t->boolean('is_disabled')->default(false);$t->timestamps();$t->unique(['bus_id','seat_number']);});
Schema::create('staff',function(Blueprint $t){$t->id();$t->foreignId('operator_id')->constrained()->cascadeOnDelete();$t->string('full_name');$t->enum('role',['driver','conductor']);$t->string('nic');$t->string('driving_licence_no')->nullable();$t->string('ntc_licence_no');$t->string('phone');$t->string('email')->nullable();$t->string('login_id')->unique();$t->string('password');$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('routes',function(Blueprint $t){$t->id();$t->foreignId('operator_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('origin');$t->string('destination');$t->unsignedInteger('duration_minutes')->nullable();$t->decimal('distance_km',8,2)->nullable();$t->decimal('base_fare',10,2)->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('route_stops',function(Blueprint $t){$t->id();$t->foreignId('route_id')->constrained()->cascadeOnDelete();$t->string('name');$t->unsignedSmallInteger('stop_order');$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->boolean('boarding_allowed')->default(true);$t->boolean('dropoff_allowed')->default(true);$t->timestamps();});
Schema::create('trips',function(Blueprint $t){$t->id();$t->foreignId('operator_id')->constrained()->cascadeOnDelete();$t->foreignId('route_id')->constrained()->cascadeOnDelete();$t->foreignId('bus_id')->constrained()->cascadeOnDelete();$t->foreignId('driver_id')->nullable()->constrained('staff')->nullOnDelete();$t->foreignId('conductor_id')->nullable()->constrained('staff')->nullOnDelete();$t->string('trip_code')->unique();$t->enum('trip_type',['starting','return']);$t->date('service_date');$t->time('departure_time');$t->time('arrival_time')->nullable();$t->decimal('fare',10,2);$t->enum('status',['scheduled','active','completed','cancelled'])->default('scheduled');$t->boolean('is_published')->default(false);$t->timestamp('started_at')->nullable();$t->timestamp('ended_at')->nullable();$t->timestamps();});
} public function down():void{foreach(['trips','route_stops','routes','staff','seats','buses','operators'] as $x)Schema::dropIfExists($x);} };