<?php
namespace App\Http\Controllers;
use App\Models\{User,Operator,Bus,Trip,Booking,Payment,SystemLog,EmergencyAlert}; use App\Support\Audit; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class AdminController extends Controller {
 public function dashboard(){ return view('admin.dashboard',['stats'=>['operators'=>Operator::count(),'buses'=>Bus::count(),'passengers'=>User::where('role','passenger')->count(),'bookings'=>Booking::count(),'activeTrips'=>Trip::where('status','active')->count(),'completedTrips'=>Trip::where('status','completed')->count(),'revenue'=>Payment::where('status','success')->sum('amount')],'recentBookings'=>Booking::with('trip.route','passenger')->latest()->take(8)->get(),'recentLogs'=>SystemLog::with('user')->latest('created_at')->take(8)->get()]); }
 public function operators(){return view('admin.operators', ['operators'=>Operator::with('user')->withCount(['buses','trips'])->latest()->paginate(20)]);}
 public function toggleOperator(Operator $operator){$operator->status=$operator->status==='active'?'inactive':'active'; $operator->is_published=$operator->status==='active'; $operator->save(); $operator->user()->update(['is_active'=>$operator->status==='active']); Audit::log('Toggle operator','Operators',$operator->company_name.' -> '.$operator->status); return back()->with('success','Operator status updated.');}
 public function passengers(){return view('admin.passengers',['passengers'=>User::where('role','passenger')->latest()->paginate(25)]);}
 public function togglePassenger(User $user){abort_unless($user->role==='passenger',404); $user->update(['is_active'=>!$user->is_active]); Audit::log('Toggle passenger','Passengers',$user->email); return back()->with('success','Passenger status updated.');}
 public function buses(){return view('admin.buses',['buses'=>Bus::with('operator')->latest()->paginate(25)]);}
 public function trips(Request $r){$q=Trip::with(['operator','bus','route','driver','conductor'])->latest('service_date'); if($r->filled('status'))$q->where('status',$r->status); return view('admin.trips',['trips'=>$q->paginate(25)]);}
 public function bookings(){return view('admin.bookings',['bookings'=>Booking::with(['trip.route','trip.operator','passenger','payment'])->latest()->paginate(25)]);}
 public function payments(){return view('admin.payments',['payments'=>Payment::with('booking.trip.operator')->latest()->paginate(25),'total'=>Payment::where('status','success')->sum('amount')]);}
 public function tracking(){return view('admin.tracking',['trips'=>Trip::with(['operator','bus','route','liveLocation'])->where('status','active')->get()]);}
 public function reports(Request $r){$from=$r->date('from')??now()->startOfMonth(); $to=$r->date('to')??now()->endOfMonth(); $payments=Payment::where('status','success')->whereBetween('paid_at',[$from->startOfDay(),$to->endOfDay()]); $data=['from'=>$from,'to'=>$to,'revenue'=>(clone $payments)->sum('amount'),'transactions'=>(clone $payments)->count(),'bookings'=>Booking::whereBetween('created_at',[$from->startOfDay(),$to->endOfDay()])->count(),'trips'=>Trip::whereBetween('service_date',[$from->toDateString(),$to->toDateString()])->count(),'operatorRevenue'=>Payment::query()->select('operators.company_name',DB::raw('SUM(payments.amount) total'))->join('bookings','bookings.id','=','payments.booking_id')->join('trips','trips.id','=','bookings.trip_id')->join('operators','operators.id','=','trips.operator_id')->where('payments.status','success')->whereBetween('payments.paid_at',[$from->startOfDay(),$to->endOfDay()])->groupBy('operators.id','operators.company_name')->orderByDesc('total')->get()]; return view('admin.reports',$data);}
 public function notifications(){return view('admin.notifications',['notifications'=>\App\Models\Notification::latest()->paginate(20)]);}
 public function sendNotification(Request $r){$d=$r->validate(['target_type'=>'required|in:all,operators,passengers','title'=>'required|max:150','message'=>'required|max:1000']); \App\Models\Notification::create($d+['sent_at'=>now()]); Audit::log('Send notification','Notifications',$d['title']); return back()->with('success','Notification recorded for delivery.');}
 public function logs(){return view('admin.logs',['logs'=>SystemLog::with('user')->latest('created_at')->paginate(40)]);}
 public function settings(){return view('admin.settings');}
 public function backup(){Audit::log('Backup requested','System','Database backup requested from admin panel'); return back()->with('success','Backup request recorded. Run: php artisan db:backup or use your hosting backup tool for the physical dump.');}
 public function alerts(){return view('admin.alerts',['alerts'=>EmergencyAlert::with(['trip.bus','trip.route','staff'])->latest()->paginate(20)]);}
}
